DROP TABLE BILHETES;


CREATE TABLE BILHETES(
    CODIGO INTEGER NOT NULL PRIMARY KEY,
    NUMERO_BILHETE VARCHAR2(32) DEFAULT (sys_guid()),
    DATA_CRIACAO DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE SEQ_CODIGO_BILHETE
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 10000000;

INSERT INTO BILHETES (CODIGO)
    VALUES  (SEQ_CODIGO_BILHETE.nextval);
    
COMMIT;

SELECT CODIGO, NUMERO_BILHETE,
    TO_CHAR(DATA_CRIACAO, 'DD-MM-YYYY HH24:MI:SS') "DATA-CRIACAO"
    FROM BILHETES;
    

SELECT SEQ_CODIGO_BILHETE.currval FROM DUAL
